process.env.DISCORD_TOKEN = 'FAKE_BOT_TOKEN';
process.env.AIRTABLE_TOKEN = 'FAKE_AIRTABLE_TOKEN';
process.env.AIRTABLE_BASE = 'FAKE_TABLE_NAME';
process.env.GUILD_ID = 'DEV_DAO_ID';
process.env.CLIENT_ID = 'FAKE_CLIENT_ID';
